GOOGLE_API_KEY: <YOUR_API_KEY>
TAVILY_API_KEY: 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
OPENAI_API_KEY: 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